### ISSUE TITLE
GGPLOT2 V3.3.0 throwing Errors

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/EmpiricalCalibration#2]
I had upgraded all my packages to run PLE and was getting this issue in plotCalibrationEffect

``` ggplot2::ggsave(fileName, plot, width = 6, height = 4.5, dpi = 400)```

```Error in frame[[1]] == ".signalSimpleWarning" : comparison (1) is possible only for atomic and list types```

Rolling back GGPLOT to V3.2.0 fixed it:
```devtools::install_github("tidyverse/ggplot2",ref = "v3.2.0")```

**Comment by schuemie** [comment]
Yes, this is a known issue. Please install ParallelLogger from the develop branch. I'm trying to release a new version of ParallelLogger, but CRAN is being difficult.

**Comment by schuemie** [comment]
Latest version of ParallelLogger is now in CRAN
